fix
Signed-off-by: Tahmid Muttaki <tmuttaki@redhat.com>

diff --git a/buildkite/test-template-fastcheck.j2 b/buildkite/test-template-fastcheck.j2
--- a/buildkite/test-template-fastcheck.j2
+++ b/buildkite/test-template-fastcheck.j2
@@ -45,18 +45,16 @@ steps:
     cancel_on_build_failing: true
     agents:
       queue: cpu_queue_premerge
-    commands:
-      - pip install pre-commit
-      - export PATH="$HOME/.local/bin:$PATH"
-      - pre-commit run --all-files --hook-stage manual
-      - |
-        #!/bin/bash
-        if [[ $? -ne 0 ]]; then
-          echo "Pre-commit checks failed. Canceling the build."
-          curl -H "Authorization: Bearer $BUILDKITE_AGENT_ACCESS_TOKEN" \
-          -X PUT "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/cancel"
-          exit 1
-        fi
+    command: |
+      pip install pre-commit
+      export PATH="$HOME/.local/bin:$PATH"
+      pre-commit run --all-files --hook-stage manual
+      if [ $? -ne 0 ]; then
+        echo "Pre-commit checks failed. Canceling the build."
+        curl -H "Authorization: Bearer $BUILDKITE_AGENT_ACCESS_TOKEN" \
+        -X PUT "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/cancel"
+        exit 1
+      fi
 
   - block: Run Neuron Test
     depends_on: ~
