add in ci
Signed-off-by: Yang Wang <elainewy@meta.com>

diff --git a/scripts/test-template-ci.j2 b/scripts/test-template-ci.j2
--- a/scripts/test-template-ci.j2
+++ b/scripts/test-template-ci.j2
@@ -245,44 +245,123 @@ steps:
   {% endif %}
   {% endfor %}
 
-- group: "vllm against torch nightly"
-  depends_on: ~
-  steps:
-    - block: Build torch nightly image
-      key: block-build-torch-nightly
-      depends_on: ~
+  - group: "vllm against torch nightly"
+    depends_on: ~
+    steps:
+      - block: Build torch nightly image
+        key: block-build-torch-nightly
+        depends_on: ~
 
-    - label: ":docker: build image torch nightly"
-      key: image-build-torch-nightly
-      depends_on: block-build-torch-nightly
+      - label: ":docker: build image torch nightly"
+        key: image-build-torch-nightly
+        depends_on: block-build-torch-nightly
+        soft_fail: true
+        agents:
+          {% if branch == "main" %}
+          queue: cpu_queue_postmerge
+          {% else %}
+          queue: cpu_queue_premerge
+          {% endif %}
+        timeout_in_minutes: 360
+        commands:
+          - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9t5s3a7"
+          - |
+            #!/bin/bash
+            if [[ -z $(docker manifest inspect {{ docker_image_torch_nightly }}) ]]; then
+              echo "Image not found, proceeding with build..."
+            else
+              echo "Image found"
+              exit 0
+            fi
+          - "docker build --file docker/Dockerfile.nightly_torch --build-arg max_jobs=16 --build-arg buildkite_commit=$BUILDKITE_COMMIT --build-arg USE_SCCACHE=1 --tag {{ docker_image_torch_nightly }} --target test --progress plain ."
+          - "docker push {{ docker_image_torch_nightly }}"
+        env:
+          DOCKER_BUILDKIT: "1"
+        retry:
+          automatic:
+            - exit_status: -1  # Agent was lost
+              limit: 2
+            - exit_status: -10  # Agent was lost
+              limit: 2
+
+    {% for step in steps %}
+    {% if step.torch_nightly and step.num_gpus<2 %}
+    {% set ns = namespace(blocked=1) %}
+
+    {% if run_all == "1" %}
+    {% set ns.blocked = 0 %}
+    {% endif %}
+
+    {% if nightly == "1" %}
+    {% set ns.blocked = 0 %}
+    {% endif %}
+
+    {% if step.source_file_dependencies %}
+      {% for source_file in step.source_file_dependencies %}
+        {% for file in list_file_diff %}
+          {% if source_file in file %}
+            {% set ns.blocked = 0 %}
+          {% endif %}
+        {% endfor %}
+      {% endfor %}
+    {% endif %}
+
+    {% if ns.blocked == 1 or (step.optional and nightly != "1") %}
+    - block: "Run Torch Nightly {{ step.label }}"
+      depends_on: image-build-torch-nightly
+      key: block-torch-nightly-{{ step.label | replace(" ", "-") | lower | replace("(", "") | replace(")", "") | replace("%", "") | replace(",", "-") }}
+    {% endif %}
+
+    - label: "{{ step.label }}"
+      {% if ns.blocked == 1 or (step.optional and nightly != "1") %}
+      depends_on: block-torch-nightly-{{ step.label | replace(" ", "-") | lower | replace("(", "") | replace(")", "") | replace("%", "") | replace(",", "-") }}
+      {% else %}
+      depends_on: image-build-torch-nightly
+      {% endif %}
       soft_fail: true
       agents:
-        {% if branch == "main" %}
-        queue: cpu_queue_postmerge
-        {% else %}
+        {% if step.no_gpu %}
         queue: cpu_queue_premerge
+        {% elif step.gpu == "a100" %}
+        queue: a100_queue
+        {% else %}
+        queue: gpu_1_queue
         {% endif %}
-      timeout_in_minutes: 360
-      commands:
-        - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9t5s3a7"
-        - |
-          #!/bin/bash
-          if [[ -z $(docker manifest inspect {{ docker_image_torch_nightly }}) ]]; then
-            echo "Image not found, proceeding with build..."
-          else
-            echo "Image found"
-            exit 0
-          fi
-        - "docker build --file docker/Dockerfile.nightly_torch --build-arg max_jobs=16 --build-arg buildkite_commit=$BUILDKITE_COMMIT --build-arg USE_SCCACHE=1 --tag {{ docker_image_torch_nightly }} --target test --progress plain ."
-        - "docker push {{ docker_image_torch_nightly }}"
-      env:
-        DOCKER_BUILDKIT: "1"
-      retry:
-        automatic:
-          - exit_status: -1  # Agent was lost
-            limit: 2
-          - exit_status: -10  # Agent was lost
-            limit: 2
+
+      {% if step.num_nodes < 2 %}
+      plugins:
+        {% if step.gpu != "a100" %}
+        - docker#v5.2.0:
+            image: {{ docker_image_torch_nightly }}
+            always-pull: true
+            propagate-environment: true
+            {% if not step.no_gpu %}
+            gpus: all
+            {% endif %}
+            {% if step.label == "Benchmarks" %}
+            mount-buildkite-agent: true
+            {% endif %}
+            command: [
+              "bash", "-xc",
+              "(command nvidia-smi || true) && export VLLM_LOGGING_LEVEL=DEBUG && export VLLM_ALLOW_DEPRECATED_BEAM_SEARCH=1 && cd {{ (step.working_dir or default_working_dir) | safe }} && {{ step.command or (step.commands | join(' && ')) | safe }}"
+            ]
+            environment:
+              - VLLM_USAGE_SOURCE=ci-test
+              - HF_HOME={{ hf_home_fsx }}
+              - HF_TOKEN
+              {% if branch == "main" %}
+              - BUILDKITE_ANALYTICS_TOKEN
+              {% endif %}
+              {% if step.label == "Speculative decoding tests" %}
+              - VLLM_ATTENTION_BACKEND=XFORMERS
+              {% endif %}
+            volumes:
+              - /dev/shm:/dev/shm
+              - {{ hf_home_fsx }}:{{ hf_home_fsx }}
+        {% endif %}
+      {% endif %}
+    {% endif %}
+    {% endfor %}
 
   - group: "AMD Tests"
     depends_on: ~
